ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.lido_anomaly_sentinel]
path = "out/LidoProtocolAnomalySentinel.sol/LidoProtocolAnomalySentinel.json"
response_contract = "0xD66D199B1583876D914B4ff2Bc2F14e5B64906ce"
response_function = "recordPooledEthCollapse(uint256,uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x689Ad0f9cBa2dA64039cF894E9fB3Aa6266861D8"]
address = "0x85E9047F1FCB5C4A14D99Ff7e702605db1D975AB"
